### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by migossss** [pabloduque0/WhiteMatterHyperintensities#1]
and what are the dependencies？Thanks for reply

**Comment by migossss** [comment]
Okay,I see the requierments,but I still don't know how to run it

**Comment by pabloduque0** [comment]
you can run it by modifying the path in: twod_runner.py and then running such file with python3. Unfortunately you would need the images which I cant add to this repo for privacy and weight reasons. You can request them yourself in the website of the WMH challenge

**Comment by migossss** [comment]
> you can run it by modifying the path in: twod_runner.py and then running such file with python3. Unfortunately you would need the images which I cant add to this repo for privacy and weight reasons. You can request them yourself in the website of the WMH challenge

Can I train it with my own dataset?

**Comment by pabloduque0** [comment]
Absolutely but you might need to make some changes in imageparser.py or make your own code to read images in the way you have them stored.

**Comment by migossss** [comment]
> Absolutely but you might need to make some changes in imageparser.py or make your own code to read images in the way you have them stored.

That help me a lot,thanks very much!

**Comment by pabloduque0** [comment]
I'll try to add some demo instructions when I have some time. In the meantime, closing this issue, let me know if you need something else

**Comment by migossss** [comment]
> I'll try to add some demo instructions when I have some time. In the meantime, closing this issue, let me know if you need something else

Okay,thanks again
