### ISSUE TITLE
New question

### ISSUE THREAD

**Issue by migossss** [pabloduque0/WhiteMatterHyperintensities#2]
I wonder what parts of a data set are composed of and what format they are in,because I have not got the data of WMH yet (I have submitted the agreement.pdf, but i think it will take some time).

**Comment by pabloduque0** [comment]
If you have requested the data, it usually doesnt take long. Each dataset has a folder with ids, and inside each of those folders there is a orig folder, a pre folder and a few other files. Check the data documentation in their website for all details.

**Comment by migossss** [comment]
> If you have requested the data, it usually doesnt take long. Each dataset has a folder with ids, and inside each of those folders there is a orig folder, a pre folder and a few other files. Check the data documentation in their website for all deI

> If you have requested the data, it usually doesnt take long. Each dataset has a folder with ids, and inside each of those folders there is a orig folder, a pre folder and a few other files. Check the data documentation in their website for all details.

I see,thank you

**Comment by migossss** [comment]
imageparser.py    line194
np_list = np.concatenate(images_list, axis=1)
It seems miss another array before axis=1?

**Comment by pabloduque0** [comment]
No, images_list is the list which will be concatenated on axis 1

**Comment by migossss** [comment]
When I run it,it shows 
np_list = np.concatenate(images_list, axis=1)
ValueError: need at least one array to concatenate
