### ISSUE TITLE
please help me again

### ISSUE THREAD

**Issue by migossss** [pabloduque0/WhiteMatterHyperintensities#3]
Utrecht:  0 0 0
Singapore:  0 0 0
Amsterdam:  0 0 0
Traceback (most recent call last):
  File "twod_runner.py", line 38, in <module>
    utrecht_normalized_t1 = parser.normalize_images(utrecht_resized_t1)
  File "/workspace/WhiteMatterHyperintensities/imageparser.py", line 194, in normalize_images
    np_list = np.concatenate(images_list, axis=1)
ValueError: need at least one array to concatenate
I dont know where are wrong,please help me

**Comment by pabloduque0** [comment]
Hello @migossss ,
Have you extracted the brains out of the original images? It looks like the parser is not picking up any files because of that reason. You can use: BET-FSL for that. The extract_all_brains function in the imageparser.py does that for you. You'll have to call it once and save the results on disk. The parser will then pick up all images with "_brain" in it.

**Comment by migossss** [comment]
> Hello @migossss ,
> Have you extracted the brains out of the original images? It looks like the parser is not picking up any files because of that reason. You can use: BET-FSL for that. The extract_all_brains function in the imageparser.py does that for you. You'll have to call it once and save the results on disk. The parser will then pick up all images with "_brain" in it.

yeah，but how to extracted the brains,I mean what command should I type. 
(Sorry for so many questions,I'm a rookie CSer,so I hope I'm not making you feel annoyed)

**Comment by pabloduque0** [comment]
> > Hello @migossss ,
> > Have you extracted the brains out of the original images? It looks like the parser is not picking up any files because of that reason. You can use: BET-FSL for that. The extract_all_brains function in the imageparser.py does that for you. You'll have to call it once and save the results on disk. The parser will then pick up all images with "_brain" in it.
> 
> yeah，but how to extracted the brains,I mean what command should I type.
> (Sorry for so many questions,I'm a rookie CSer,so I hope I'm not making you feel annoyed)

Create a new script that imports imageparser.py and calls that function that I mentioned in my last comment.

**Comment by migossss** [comment]
After you have downloaded the dataset,how did you  process the dataset?I mean when you run this project ,what's in the dataset folder.

**Comment by pabloduque0** [comment]
> After you have downloaded the dataset,how did you process the dataset?I mean when you run this project ,what's in the dataset folder.

I added demo info for running the project. Hope it helps

**Comment by migossss** [comment]
> > After you have downloaded the dataset,how did you process the dataset?I mean when you run this project ,what's in the dataset folder.
> 
> I added demo info for running the project. Hope it helps

That helps me a lot,I know what to do,thank you!
